Repository kodesalon/project, pull requests merged in 2021-06, with the labels that each got.

#32 Feature/#16 Refactor/#31
  build.gradle
  src/main/java/com/project/kodesalon/model/member/domain/Member.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Alias.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Email.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Name.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Password.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Phone.java
  src/main/resources/application.yml
  src/test/java/com/project/kodesalon/model/member/domain/MemberTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/AliasTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/EmailTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/NameTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/PasswordTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/PhoneTest.java
Labels: PR: partially-approved

#38 Feature/#17/게시물 도메인 구현
  src/main/java/com/project/kodesalon/model/board/domain/Board.java
  src/test/java/com/project/kodesalon/model/board/domain/BoardTest.java
Labels: PR: reviewed-approved

#39 Feature/#21/게시물 작성 기능 구현
  src/docs/asciidoc/kodesalonApi.adoc
  src/main/java/com/project/kodesalon/common/ErrorResponse.java
  src/main/java/com/project/kodesalon/common/GlobalExceptionHandler.java
  src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
  src/main/java/com/project/kodesalon/model/board/controller/dto/BoardCreateRequest.java
  src/main/java/com/project/kodesalon/model/board/domain/Board.java
  src/main/java/com/project/kodesalon/model/board/exception/InvalidArgumentException.java
  src/main/java/com/project/kodesalon/model/board/repository/BoardRepository.java
  src/main/java/com/project/kodesalon/model/board/service/BoardService.java
  src/main/java/com/project/kodesalon/model/board/service/dto/BoardCreateRequestDto.java
  src/main/resources/static/docs/kodesalonApi.html
  src/test/java/com/project/kodesalon/config/JacksonConfiguration.java
  src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
  src/test/java/com/project/kodesalon/model/board/controller/dto/BoardCreateRequestTest.java
  src/test/java/com/project/kodesalon/model/board/domain/BoardTest.java
  src/test/java/com/project/kodesalon/model/board/domain/vo/ContentTest.java
  src/test/java/com/project/kodesalon/model/board/domain/vo/TitleTest.java
  src/test/java/com/project/kodesalon/model/board/repository/BoardRepositoryTest.java
  src/test/java/com/project/kodesalon/model/board/service/BoardServiceTest.java
  src/test/java/com/project/kodesalon/model/board/service/dto/BoardCreateRequestDtoTest.java
  src/test/java/com/project/kodesalon/utils/ApiDocumentUtils.java
Labels: PR: unreviewed

#36 Feature/#20/회원 로그인 기능 구현
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/project/kodesalon/common/ErrorResponse.java
  src/main/java/com/project/kodesalon/common/GlobalExceptionHandler.java
  src/main/java/com/project/kodesalon/model/member/controller/MemberController.java
  src/main/java/com/project/kodesalon/model/member/controller/dto/LoginRequest.java
  src/main/java/com/project/kodesalon/model/member/domain/Member.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Alias.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Email.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Name.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Password.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Phone.java
  src/main/java/com/project/kodesalon/model/member/repository/MemberRepository.java
  src/main/java/com/project/kodesalon/model/member/service/MemberService.java
  src/main/java/com/project/kodesalon/model/member/service/dto/LoginRequestDto.java
  src/main/java/com/project/kodesalon/model/member/service/dto/LoginResponseDto.java
  src/main/resources/static/docs/api-docs.html
  src/test/java/com/project/kodesalon/common/ErrorResponseTest.java
  src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
  src/test/java/com/project/kodesalon/model/member/controller/dto/LoginRequestTest.java
  src/test/java/com/project/kodesalon/model/member/domain/MemberTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/AliasTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/EmailTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/NameTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/PasswordTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/PhoneTest.java
  src/test/java/com/project/kodesalon/model/member/repository/MemberRepositoryTest.java
  src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/LoginRequestDtoTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/LoginResponseDtoTest.java
Labels: PR: unreviewed

#48 1차 배포 - 회원 로그인 기능 추가
  .gitignore
  appspec.yml
  build.gradle
  lombok.config
  scripts/deploy.sh
  scripts/kill_process.sh
  src/docs/asciidoc/api-docs.adoc
  src/docs/asciidoc/kodesalonApi.adoc
  src/main/java/com/project/kodesalon/common/ErrorResponse.java
  src/main/java/com/project/kodesalon/common/GlobalExceptionHandler.java
  src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
  src/main/java/com/project/kodesalon/model/board/controller/dto/BoardCreateRequest.java
  src/main/java/com/project/kodesalon/model/board/domain/Board.java
  src/main/java/com/project/kodesalon/model/board/domain/vo/Content.java
  src/main/java/com/project/kodesalon/model/board/domain/vo/Title.java
  src/main/java/com/project/kodesalon/model/board/exception/InvalidArgumentException.java
  src/main/java/com/project/kodesalon/model/board/repository/BoardRepository.java
  src/main/java/com/project/kodesalon/model/board/service/BoardService.java
  src/main/java/com/project/kodesalon/model/board/service/dto/BoardCreateRequestDto.java
  src/main/java/com/project/kodesalon/model/member/controller/MemberController.java
  src/main/java/com/project/kodesalon/model/member/controller/dto/LoginRequest.java
  src/main/java/com/project/kodesalon/model/member/domain/Member.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Alias.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Email.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Name.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Password.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Phone.java
  src/main/java/com/project/kodesalon/model/member/repository/MemberRepository.java
  src/main/java/com/project/kodesalon/model/member/service/MemberService.java
  src/main/java/com/project/kodesalon/model/member/service/dto/LoginRequestDto.java
  src/main/java/com/project/kodesalon/model/member/service/dto/LoginResponseDto.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/main/resources/static/docs/api-docs.html
  src/main/resources/static/docs/kodesalonApi.html
  src/test/java/com/project/kodesalon/KodesalonApplicationTests.java
  src/test/java/com/project/kodesalon/common/ErrorResponseTest.java
  src/test/java/com/project/kodesalon/config/JacksonConfiguration.java
  src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
  src/test/java/com/project/kodesalon/model/board/controller/dto/BoardCreateRequestTest.java
  src/test/java/com/project/kodesalon/model/board/domain/BoardTest.java
  src/test/java/com/project/kodesalon/model/board/domain/vo/ContentTest.java
  src/test/java/com/project/kodesalon/model/board/domain/vo/TitleTest.java
  src/test/java/com/project/kodesalon/model/board/repository/BoardRepositoryTest.java
  src/test/java/com/project/kodesalon/model/board/service/BoardServiceTest.java
  src/test/java/com/project/kodesalon/model/board/service/dto/BoardCreateRequestDtoTest.java
  src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
  src/test/java/com/project/kodesalon/model/member/controller/dto/LoginRequestTest.java
  src/test/java/com/project/kodesalon/model/member/domain/MemberTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/AliasTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/EmailTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/NameTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/PasswordTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/PhoneTest.java
  src/test/java/com/project/kodesalon/model/member/repository/MemberRepositoryTest.java
  src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/LoginRequestDtoTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/LoginResponseDtoTest.java
  src/test/java/com/project/kodesalon/utils/ApiDocumentUtils.java
Labels: PR: reviewed-approved

#40 Feature/#18/회원가입 기능 구현
  build.gradle
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/project/kodesalon/common/BaseEntity.java
  src/main/java/com/project/kodesalon/common/GlobalExceptionHandler.java
  src/main/java/com/project/kodesalon/model/member/controller/MemberController.java
  src/main/java/com/project/kodesalon/model/member/controller/dto/LoginRequest.java
  src/main/java/com/project/kodesalon/model/member/domain/Member.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Alias.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Email.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Name.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Password.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Phone.java
  src/main/java/com/project/kodesalon/model/member/service/MemberService.java
  src/main/java/com/project/kodesalon/model/member/service/dto/CreateMemberRequest.java
  src/main/java/com/project/kodesalon/model/member/service/dto/LoginRequest.java
  src/main/java/com/project/kodesalon/model/member/service/dto/LoginRequestDto.java
  src/main/java/com/project/kodesalon/model/member/service/dto/LoginResponse.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/main/resources/static/docs/api-docs.html
  src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
  src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
  src/test/java/com/project/kodesalon/model/member/controller/dto/LoginRequestTest.java
  src/test/java/com/project/kodesalon/model/member/domain/MemberTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/AliasTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/EmailTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/NameTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/PasswordTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/PhoneTest.java
  src/test/java/com/project/kodesalon/model/member/repository/MemberRepositoryTest.java
  src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/CreateMemberRequestTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/LoginRequestDtoTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/LoginRequestTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/LoginResponseTest.java
Labels: PR: unreviewed

#42 Feature/#41/회원 조회 기능 구현
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/project/kodesalon/model/member/controller/MemberController.java
  src/main/java/com/project/kodesalon/model/member/domain/Member.java
  src/main/java/com/project/kodesalon/model/member/service/MemberService.java
  src/main/java/com/project/kodesalon/model/member/service/dto/SelectMemberResponse.java
  src/main/resources/static/docs/api-docs.html
  src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
  src/test/java/com/project/kodesalon/model/member/domain/MemberTest.java
  src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/LoginRequestTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/LoginResponseTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/SelectMemberResponseTest.java
Labels: PR: unreviewed

#56 2차 배포
  build.gradle
  src/docs/asciidoc/api-docs.adoc
  src/main/java/com/project/kodesalon/common/BaseEntity.java
  src/main/java/com/project/kodesalon/common/GlobalExceptionHandler.java
  src/main/java/com/project/kodesalon/model/member/controller/MemberController.java
  src/main/java/com/project/kodesalon/model/member/controller/dto/LoginRequest.java
  src/main/java/com/project/kodesalon/model/member/domain/Member.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Alias.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Email.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Name.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Password.java
  src/main/java/com/project/kodesalon/model/member/domain/vo/Phone.java
  src/main/java/com/project/kodesalon/model/member/repository/MemberRepository.java
  src/main/java/com/project/kodesalon/model/member/service/MemberService.java
  src/main/java/com/project/kodesalon/model/member/service/dto/ChangePasswordRequest.java
  src/main/java/com/project/kodesalon/model/member/service/dto/ChangePasswordResponse.java
  src/main/java/com/project/kodesalon/model/member/service/dto/CreateMemberRequest.java
  src/main/java/com/project/kodesalon/model/member/service/dto/LoginRequest.java
  src/main/java/com/project/kodesalon/model/member/service/dto/LoginRequestDto.java
  src/main/java/com/project/kodesalon/model/member/service/dto/LoginResponse.java
  src/main/java/com/project/kodesalon/model/member/service/dto/SelectMemberResponse.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/main/resources/static/docs/api-docs.html
  src/main/resources/static/docs/kodesalonApi.html
  src/test/java/com/project/kodesalon/common/ErrorResponseTest.java
  src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
  src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
  src/test/java/com/project/kodesalon/model/member/controller/dto/LoginRequestTest.java
  src/test/java/com/project/kodesalon/model/member/domain/MemberTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/AliasTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/EmailTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/NameTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/PasswordTest.java
  src/test/java/com/project/kodesalon/model/member/domain/vo/PhoneTest.java
  src/test/java/com/project/kodesalon/model/member/repository/MemberRepositoryTest.java
  src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/ChangePasswordResponseTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/CreateMemberRequestTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/LoginRequestDtoTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/LoginRequestTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/LoginResponseTest.java
  src/test/java/com/project/kodesalon/model/member/service/dto/SelectMemberResponseTest.java
Labels: PR: reviewed-approved
